const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

function escapeForTemplateLiteral(code) {
    return code
        .replace(/\\/g, '\\\\')
        .replace(/`/g, '\\`')
        .replace(/\$\{/g, '\\${')
        .replace(/<\/script>/gi, '<\\/script>');
}

function resolveDistFile(repoDir) {
    const candidates = [
        path.join(repoDir, 'dist/openpgp.min.js'),
        path.join(repoDir, 'dist/lightweight/openpgp.min.js'),
    ];
    for (const p of candidates) {
        if (fs.existsSync(p)) return p;
    }
    throw new Error(`Could not find built openpgp bundle. Checked:\n- ${candidates.join('\n- ')}`);
}

function applyPatch(bundle) {
    let patched = bundle;

    // Patch 1: add subkeys to reformatKey signature
    patched = patched.replace(
        /function\(\{privateKey:e,userIDs:t=\[\],passphrase:r,keyExpirationTime:i=0,date:n,format:a="armored",config:s,\.\.\.o\}\)/s,
        'function({privateKey:e,userIDs:t=[],passphrase:r,keyExpirationTime:i=0,date:n,format:a="armored",config:s,subkeys:l,...o})'
    );

    // Patch 2: forward subkeys into options object
    patched = patched.replace(
        /const u=\{privateKey:e,userIDs:t,passphrase:r,keyExpirationTime:i,date:n\}/,
        'const u={privateKey:e,userIDs:t,passphrase:r,keyExpirationTime:i,date:n,subkeys:l}'
    );

    return patched;
}

function patchOpenPGP() {
    const repoUrl = 'https://github.com/openpgpjs/openpgpjs.git';
    const repoDir = path.resolve(__dirname, '../openpgpjs');
    const assetsDir = path.resolve(__dirname, '../assets/pgp');
    const wrapperFile = path.join(assetsDir, 'openpgp.bundle.js');

    // Case 1: bundle already exists
    if (fs.existsSync(wrapperFile)) {
        let existing = fs.readFileSync(wrapperFile, 'utf8');
        if (existing.includes('subkeys:l')) {
            return;
        }
        const unwrapped = existing.replace(/^\/\/ Generated[\s\S]*?export default `\n/, '').replace(/`\n;?\s*$/, '');
        const patched = applyPatch(unwrapped);
        const wrapped = `// Generated by patch-openpgp\nexport default \`\n${escapeForTemplateLiteral(patched)}\n\`;\n`;
        fs.writeFileSync(wrapperFile, wrapped, 'utf8');
        return;
    }

    // Case 2: bundle missing → clone, build, patch, wrap, then delete repo
    if (!fs.existsSync(repoDir)) {
        execSync(`git clone ${repoUrl} ${repoDir}`, { stdio: 'inherit' });
    }
    execSync('git fetch --all', { cwd: repoDir, stdio: 'inherit' });
    execSync('git checkout v5.11.3', { cwd: repoDir, stdio: 'inherit' });
    execSync('npm install', { cwd: repoDir, stdio: 'inherit' });
    execSync('npm run build', { cwd: repoDir, stdio: 'inherit' });

    const distFile = resolveDistFile(repoDir);
    let bundle = fs.readFileSync(distFile, 'utf8');
    bundle = applyPatch(bundle);

    if (!fs.existsSync(assetsDir)) {
        fs.mkdirSync(assetsDir, { recursive: true });
    }
    const wrapped = `// Generated by patch-openpgp\nexport default \`\n${escapeForTemplateLiteral(bundle)}\n\`;\n`;
    fs.writeFileSync(wrapperFile, wrapped, 'utf8');

    // Clean up repo
    fs.rmSync(repoDir, { recursive: true, force: true });
}

module.exports = function withPatchOpenPGP(config) {
    patchOpenPGP();
    return config;
};